
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import Footer from "./components/Footers";
import SessionWrapper from "./components/SessionWrapper";

export const metadata: Metadata = {
  title: "apap",
  description: "Generated by create next app",
  
};
export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <SessionWrapper>
    <html lang="en">
      <head>
        {/* You can also add other meta tags or link tags here */}
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <Navbar />
        
        <main>{children}</main>
        
       <Footer/>
      </body>
      
    </html>
    </SessionWrapper>
  );
}



